const STATUS_LABELS: Record<string, string> = {
  active: 'Activo',
  inactive: 'Inactivo',
  disabled: 'Desactivado',
  disconnected: 'Desconectado',
  archived: 'Archivado',
  pending: 'Pendiente',
  completed: 'Completado',
  approved: 'Aprobado',
  rejected: 'Rechazado',
  scheduled: 'Programado',
  strategic: 'Estratégica',
  weekly: 'Semanal',
  onboarding: 'Incorporación',
  paused: 'Pausado',
  error: 'Error',
  review: 'En revisión',
  draft: 'Borrador',
  new: 'Nuevo',
  contacted: 'Contactado',
  qualified: 'Calificado',
  discarded: 'Descartado',
  converted: 'Convertido',
  won: 'Ganado',
  lost: 'Perdido',
  in_progress: 'En progreso',
  internal_review: 'Revisión interna',
  client_validation: 'Validación del cliente',
  on_hold: 'En espera',
  blocked: 'Bloqueado',
  cancelled: 'Cancelado',
  meeting_scheduled: 'Reunión agendada',
  quote_sent: 'Cotización enviada',
  negotiation: 'Negociación',
  assigned: 'Asignado',
  correction: 'Corrección',
  delivered: 'Entregado',
  requested: 'Solicitado',
  sent: 'Enviado',
  submitted: 'Enviado a revisión',
  received: 'Recibido',
  viewed: 'Visto',
  ended: 'Finalizado',
  published: 'Publicado',
  pending_pricing: 'Pendiente de valorización',
  ready_to_invoice: 'Listo para facturar',
  confirmed: 'Confirmada',
  attended: 'Asistió',
  no_show: 'No asistió',
  rescheduled: 'Reagendada',
  cancelled_client: 'Cancelada por cliente',
  cancelled_business: 'Cancelada por empresa',
  waitlist: 'Lista de espera',
  open: 'Pendiente',
  done: 'Completado',
};

export function statusLabel(status: string): string {
  return STATUS_LABELS[status] ?? status
    .replace(/_/g, ' ')
    .replace(/^./, (character) => character.toUpperCase());
}
