import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * `invoices.number` and `quotes.number` were created with a column-level
 * UNIQUE constraint (0008-create-billing-catalog.ts), which is global across
 * the whole database rather than scoped per organization. In a multi-tenant
 * app this means two unrelated organizations can't both use "INV-001", and
 * lets one org infer whether a specific invoice number exists in another
 * org's data via a 409 collision. The correct constraint is
 * UNIQUE(organization_id, number).
 *
 * The old unique index name isn't fixed in code (it was auto-generated by
 * MySQL from `isUnique: true`), so this migration looks it up from
 * information_schema instead of hardcoding a guess.
 */
export class ScopeInvoiceQuoteNumberPerOrg1721765000000 implements MigrationInterface {
  name = 'ScopeInvoiceQuoteNumberPerOrg1721765000000';

  private async findUniqueIndexOnColumn(queryRunner: QueryRunner, table: string, column: string): Promise<string | undefined> {
    const rows: Array<{ INDEX_NAME: string }> = await queryRunner.query(
      `SELECT DISTINCT INDEX_NAME FROM information_schema.STATISTICS
       WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND COLUMN_NAME = ? AND NON_UNIQUE = 0 AND INDEX_NAME != 'PRIMARY'`,
      [table, column],
    );
    return rows[0]?.INDEX_NAME;
  }

  public async up(queryRunner: QueryRunner): Promise<void> {
    const invoiceIndex = await this.findUniqueIndexOnColumn(queryRunner, 'invoices', 'number');
    if (invoiceIndex) await queryRunner.query(`ALTER TABLE invoices DROP INDEX \`${invoiceIndex}\``);
    await queryRunner.query('ALTER TABLE invoices ADD UNIQUE INDEX UQ_invoices_org_number (organization_id, number)');

    const quoteIndex = await this.findUniqueIndexOnColumn(queryRunner, 'quotes', 'number');
    if (quoteIndex) await queryRunner.query(`ALTER TABLE quotes DROP INDEX \`${quoteIndex}\``);
    await queryRunner.query('ALTER TABLE quotes ADD UNIQUE INDEX UQ_quotes_org_number (organization_id, number)');
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE invoices DROP INDEX UQ_invoices_org_number');
    await queryRunner.query('ALTER TABLE invoices ADD UNIQUE INDEX number (number)');
    await queryRunner.query('ALTER TABLE quotes DROP INDEX UQ_quotes_org_number');
    await queryRunner.query('ALTER TABLE quotes ADD UNIQUE INDEX number (number)');
  }
}
